# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: outerskyb
google_analytics: outerskyb
title: outerskyb

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: outersky

description: outerskyb blog
author:
  name: outerskyb
  email: outerskyb@gmail.com
  github: outerskyb
  bio: |-
   1. associate to every thing while foucing on meaning. (외연을 최대한 넓게 가지는 동시에 의미에 집중한다.) 
   
   2. knowing diffrences among almost same things, knowing equivalence among different things. (같은 것들 중에서 다름을 보고, 다른 것들 중에서 같음을 본다.)


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
